vich_uploader:
    db_driver: orm

    mappings:
        res_img:
            uri_prefix: '%app.path.resource_Image%'
            upload_destination: '%kernel.project_dir%/public/%app.path.resource_Image%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        res_content:
            uri_prefix: '%app.path.resource_File%'
            upload_destination: '%kernel.project_dir%/public/%app.path.resource_File%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

